(cl:defpackage rosplan_interface_mapping-srv
  (:use )
  (:export
   "ADDWAYPOINT"
   "<ADDWAYPOINT-REQUEST>"
   "ADDWAYPOINT-REQUEST"
   "<ADDWAYPOINT-RESPONSE>"
   "ADDWAYPOINT-RESPONSE"
   "CREATEPRM"
   "<CREATEPRM-REQUEST>"
   "CREATEPRM-REQUEST"
   "<CREATEPRM-RESPONSE>"
   "CREATEPRM-RESPONSE"
   "REMOVEWAYPOINT"
   "<REMOVEWAYPOINT-REQUEST>"
   "REMOVEWAYPOINT-REQUEST"
   "<REMOVEWAYPOINT-RESPONSE>"
   "REMOVEWAYPOINT-RESPONSE"
  ))

