// Generated by gencpp from file rosplan_interface_mapping/AddWaypointRequest.msg
// DO NOT EDIT!


#ifndef ROSPLAN_INTERFACE_MAPPING_MESSAGE_ADDWAYPOINTREQUEST_H
#define ROSPLAN_INTERFACE_MAPPING_MESSAGE_ADDWAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace rosplan_interface_mapping
{
template <class ContainerAllocator>
struct AddWaypointRequest_
{
  typedef AddWaypointRequest_<ContainerAllocator> Type;

  AddWaypointRequest_()
    : id()
    , waypoint()
    , connecting_distance(0.0)  {
    }
  AddWaypointRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , waypoint(_alloc)
    , connecting_distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _waypoint_type;
  _waypoint_type waypoint;

   typedef float _connecting_distance_type;
  _connecting_distance_type connecting_distance;





  typedef boost::shared_ptr< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddWaypointRequest_

typedef ::rosplan_interface_mapping::AddWaypointRequest_<std::allocator<void> > AddWaypointRequest;

typedef boost::shared_ptr< ::rosplan_interface_mapping::AddWaypointRequest > AddWaypointRequestPtr;
typedef boost::shared_ptr< ::rosplan_interface_mapping::AddWaypointRequest const> AddWaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator1> & lhs, const ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.waypoint == rhs.waypoint &&
    lhs.connecting_distance == rhs.connecting_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator1> & lhs, const ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_interface_mapping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd9af2cdf47b3141d3559a7b37e0fa5a";
  }

  static const char* value(const ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd9af2cdf47b3141ULL;
  static const uint64_t static_value2 = 0xd3559a7b37e0fa5aULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_interface_mapping/AddWaypointRequest";
  }

  static const char* value(const ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
"geometry_msgs/PoseStamped waypoint\n"
"float32 connecting_distance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.waypoint);
      stream.next(m.connecting_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddWaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_interface_mapping::AddWaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "waypoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoint);
    s << indent << "connecting_distance: ";
    Printer<float>::stream(s, indent + "  ", v.connecting_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_INTERFACE_MAPPING_MESSAGE_ADDWAYPOINTREQUEST_H
