// Generated by gencpp from file rosplan_interface_mapping/CreatePRM.msg
// DO NOT EDIT!


#ifndef ROSPLAN_INTERFACE_MAPPING_MESSAGE_CREATEPRM_H
#define ROSPLAN_INTERFACE_MAPPING_MESSAGE_CREATEPRM_H

#include <ros/service_traits.h>


#include <rosplan_interface_mapping/CreatePRMRequest.h>
#include <rosplan_interface_mapping/CreatePRMResponse.h>


namespace rosplan_interface_mapping
{

struct CreatePRM
{

typedef CreatePRMRequest Request;
typedef CreatePRMResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CreatePRM
} // namespace rosplan_interface_mapping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosplan_interface_mapping::CreatePRM > {
  static const char* value()
  {
    return "e2d990767484410646d05d82e9a4545b";
  }

  static const char* value(const ::rosplan_interface_mapping::CreatePRM&) { return value(); }
};

template<>
struct DataType< ::rosplan_interface_mapping::CreatePRM > {
  static const char* value()
  {
    return "rosplan_interface_mapping/CreatePRM";
  }

  static const char* value(const ::rosplan_interface_mapping::CreatePRM&) { return value(); }
};


// service_traits::MD5Sum< ::rosplan_interface_mapping::CreatePRMRequest> should match
// service_traits::MD5Sum< ::rosplan_interface_mapping::CreatePRM >
template<>
struct MD5Sum< ::rosplan_interface_mapping::CreatePRMRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_interface_mapping::CreatePRM >::value();
  }
  static const char* value(const ::rosplan_interface_mapping::CreatePRMRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_interface_mapping::CreatePRMRequest> should match
// service_traits::DataType< ::rosplan_interface_mapping::CreatePRM >
template<>
struct DataType< ::rosplan_interface_mapping::CreatePRMRequest>
{
  static const char* value()
  {
    return DataType< ::rosplan_interface_mapping::CreatePRM >::value();
  }
  static const char* value(const ::rosplan_interface_mapping::CreatePRMRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosplan_interface_mapping::CreatePRMResponse> should match
// service_traits::MD5Sum< ::rosplan_interface_mapping::CreatePRM >
template<>
struct MD5Sum< ::rosplan_interface_mapping::CreatePRMResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_interface_mapping::CreatePRM >::value();
  }
  static const char* value(const ::rosplan_interface_mapping::CreatePRMResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_interface_mapping::CreatePRMResponse> should match
// service_traits::DataType< ::rosplan_interface_mapping::CreatePRM >
template<>
struct DataType< ::rosplan_interface_mapping::CreatePRMResponse>
{
  static const char* value()
  {
    return DataType< ::rosplan_interface_mapping::CreatePRM >::value();
  }
  static const char* value(const ::rosplan_interface_mapping::CreatePRMResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPLAN_INTERFACE_MAPPING_MESSAGE_CREATEPRM_H
