// Generated by gencpp from file rosplan_interface_mapping/RemoveWaypointResponse.msg
// DO NOT EDIT!


#ifndef ROSPLAN_INTERFACE_MAPPING_MESSAGE_REMOVEWAYPOINTRESPONSE_H
#define ROSPLAN_INTERFACE_MAPPING_MESSAGE_REMOVEWAYPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_interface_mapping
{
template <class ContainerAllocator>
struct RemoveWaypointResponse_
{
  typedef RemoveWaypointResponse_<ContainerAllocator> Type;

  RemoveWaypointResponse_()
    {
    }
  RemoveWaypointResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveWaypointResponse_

typedef ::rosplan_interface_mapping::RemoveWaypointResponse_<std::allocator<void> > RemoveWaypointResponse;

typedef boost::shared_ptr< ::rosplan_interface_mapping::RemoveWaypointResponse > RemoveWaypointResponsePtr;
typedef boost::shared_ptr< ::rosplan_interface_mapping::RemoveWaypointResponse const> RemoveWaypointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rosplan_interface_mapping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_interface_mapping/RemoveWaypointResponse";
  }

  static const char* value(const ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveWaypointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rosplan_interface_mapping::RemoveWaypointResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_INTERFACE_MAPPING_MESSAGE_REMOVEWAYPOINTRESPONSE_H
