// Generated by gencpp from file rosplan_interface_mapping/RemoveWaypoint.msg
// DO NOT EDIT!


#ifndef ROSPLAN_INTERFACE_MAPPING_MESSAGE_REMOVEWAYPOINT_H
#define ROSPLAN_INTERFACE_MAPPING_MESSAGE_REMOVEWAYPOINT_H

#include <ros/service_traits.h>


#include <rosplan_interface_mapping/RemoveWaypointRequest.h>
#include <rosplan_interface_mapping/RemoveWaypointResponse.h>


namespace rosplan_interface_mapping
{

struct RemoveWaypoint
{

typedef RemoveWaypointRequest Request;
typedef RemoveWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveWaypoint
} // namespace rosplan_interface_mapping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosplan_interface_mapping::RemoveWaypoint > {
  static const char* value()
  {
    return "bbfcda76036ebbe3d36caf7af80b260c";
  }

  static const char* value(const ::rosplan_interface_mapping::RemoveWaypoint&) { return value(); }
};

template<>
struct DataType< ::rosplan_interface_mapping::RemoveWaypoint > {
  static const char* value()
  {
    return "rosplan_interface_mapping/RemoveWaypoint";
  }

  static const char* value(const ::rosplan_interface_mapping::RemoveWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::rosplan_interface_mapping::RemoveWaypointRequest> should match
// service_traits::MD5Sum< ::rosplan_interface_mapping::RemoveWaypoint >
template<>
struct MD5Sum< ::rosplan_interface_mapping::RemoveWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_interface_mapping::RemoveWaypoint >::value();
  }
  static const char* value(const ::rosplan_interface_mapping::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_interface_mapping::RemoveWaypointRequest> should match
// service_traits::DataType< ::rosplan_interface_mapping::RemoveWaypoint >
template<>
struct DataType< ::rosplan_interface_mapping::RemoveWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::rosplan_interface_mapping::RemoveWaypoint >::value();
  }
  static const char* value(const ::rosplan_interface_mapping::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosplan_interface_mapping::RemoveWaypointResponse> should match
// service_traits::MD5Sum< ::rosplan_interface_mapping::RemoveWaypoint >
template<>
struct MD5Sum< ::rosplan_interface_mapping::RemoveWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_interface_mapping::RemoveWaypoint >::value();
  }
  static const char* value(const ::rosplan_interface_mapping::RemoveWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_interface_mapping::RemoveWaypointResponse> should match
// service_traits::DataType< ::rosplan_interface_mapping::RemoveWaypoint >
template<>
struct DataType< ::rosplan_interface_mapping::RemoveWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::rosplan_interface_mapping::RemoveWaypoint >::value();
  }
  static const char* value(const ::rosplan_interface_mapping::RemoveWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPLAN_INTERFACE_MAPPING_MESSAGE_REMOVEWAYPOINT_H
