// Generated by gencpp from file rosplan_knowledge_msgs/GetEnumerableTypeService.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETENUMERABLETYPESERVICE_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETENUMERABLETYPESERVICE_H

#include <ros/service_traits.h>


#include <rosplan_knowledge_msgs/GetEnumerableTypeServiceRequest.h>
#include <rosplan_knowledge_msgs/GetEnumerableTypeServiceResponse.h>


namespace rosplan_knowledge_msgs
{

struct GetEnumerableTypeService
{

typedef GetEnumerableTypeServiceRequest Request;
typedef GetEnumerableTypeServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEnumerableTypeService
} // namespace rosplan_knowledge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeService > {
  static const char* value()
  {
    return "620e0db27dedf37a3e89c5aaa3324d1b";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetEnumerableTypeService&) { return value(); }
};

template<>
struct DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeService > {
  static const char* value()
  {
    return "rosplan_knowledge_msgs/GetEnumerableTypeService";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetEnumerableTypeService&) { return value(); }
};


// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceRequest> should match
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeService >
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceRequest> should match
// service_traits::DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeService >
template<>
struct DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse> should match
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeService >
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse> should match
// service_traits::DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeService >
template<>
struct DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETENUMERABLETYPESERVICE_H
