// Generated by gencpp from file rosplan_knowledge_msgs/GetEnumerableTypeServiceResponse.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETENUMERABLETYPESERVICERESPONSE_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETENUMERABLETYPESERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_knowledge_msgs
{
template <class ContainerAllocator>
struct GetEnumerableTypeServiceResponse_
{
  typedef GetEnumerableTypeServiceResponse_<ContainerAllocator> Type;

  GetEnumerableTypeServiceResponse_()
    : values()  {
    }
  GetEnumerableTypeServiceResponse_(const ContainerAllocator& _alloc)
    : values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetEnumerableTypeServiceResponse_

typedef ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<std::allocator<void> > GetEnumerableTypeServiceResponse;

typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse > GetEnumerableTypeServiceResponsePtr;
typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse const> GetEnumerableTypeServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_knowledge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b574a4a611cba2b6cf401af98173eb55";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb574a4a611cba2b6ULL;
  static const uint64_t static_value2 = 0xcf401af98173eb55ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_knowledge_msgs/GetEnumerableTypeServiceResponse";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] values\n"
"\n"
;
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEnumerableTypeServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_knowledge_msgs::GetEnumerableTypeServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETENUMERABLETYPESERVICERESPONSE_H
