// Generated by gencpp from file rosplan_knowledge_msgs/GetRDDLFluentTypeRequest.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETRDDLFLUENTTYPEREQUEST_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETRDDLFLUENTTYPEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_knowledge_msgs
{
template <class ContainerAllocator>
struct GetRDDLFluentTypeRequest_
{
  typedef GetRDDLFluentTypeRequest_<ContainerAllocator> Type;

  GetRDDLFluentTypeRequest_()
    : fluent_name()  {
    }
  GetRDDLFluentTypeRequest_(const ContainerAllocator& _alloc)
    : fluent_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fluent_name_type;
  _fluent_name_type fluent_name;





  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetRDDLFluentTypeRequest_

typedef ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<std::allocator<void> > GetRDDLFluentTypeRequest;

typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest > GetRDDLFluentTypeRequestPtr;
typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest const> GetRDDLFluentTypeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.fluent_name == rhs.fluent_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_knowledge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "729c00ebba1cfd63f67bdf5246417168";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x729c00ebba1cfd63ULL;
  static const uint64_t static_value2 = 0xf67bdf5246417168ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_knowledge_msgs/GetRDDLFluentTypeRequest";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Get all values of the enumeration type with the name 'typeName'.\n"
"string fluent_name\n"
;
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fluent_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRDDLFluentTypeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_knowledge_msgs::GetRDDLFluentTypeRequest_<ContainerAllocator>& v)
  {
    s << indent << "fluent_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fluent_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETRDDLFLUENTTYPEREQUEST_H
