// Generated by gencpp from file rosplan_knowledge_msgs/GetRDDLImmediateRewardResponse.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETRDDLIMMEDIATEREWARDRESPONSE_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETRDDLIMMEDIATEREWARDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_knowledge_msgs
{
template <class ContainerAllocator>
struct GetRDDLImmediateRewardResponse_
{
  typedef GetRDDLImmediateRewardResponse_<ContainerAllocator> Type;

  GetRDDLImmediateRewardResponse_()
    : reward(0.0)  {
    }
  GetRDDLImmediateRewardResponse_(const ContainerAllocator& _alloc)
    : reward(0.0)  {
  (void)_alloc;
    }



   typedef double _reward_type;
  _reward_type reward;





  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRDDLImmediateRewardResponse_

typedef ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<std::allocator<void> > GetRDDLImmediateRewardResponse;

typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse > GetRDDLImmediateRewardResponsePtr;
typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse const> GetRDDLImmediateRewardResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reward == rhs.reward;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_knowledge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "771556160cdcd4a7d44d50647196f540";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x771556160cdcd4a7ULL;
  static const uint64_t static_value2 = 0xd44d50647196f540ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_knowledge_msgs/GetRDDLImmediateRewardResponse";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 reward\n"
"\n"
;
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRDDLImmediateRewardResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_knowledge_msgs::GetRDDLImmediateRewardResponse_<ContainerAllocator>& v)
  {
    s << indent << "reward: ";
    Printer<double>::stream(s, indent + "  ", v.reward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETRDDLIMMEDIATEREWARDRESPONSE_H
