// Generated by gencpp from file rosplan_knowledge_msgs/GetRDDLParamsResponse.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETRDDLPARAMSRESPONSE_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETRDDLPARAMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_knowledge_msgs
{
template <class ContainerAllocator>
struct GetRDDLParamsResponse_
{
  typedef GetRDDLParamsResponse_<ContainerAllocator> Type;

  GetRDDLParamsResponse_()
    : horizon(0)
    , discount_factor(0.0)
    , max_nondef_actions(0)  {
    }
  GetRDDLParamsResponse_(const ContainerAllocator& _alloc)
    : horizon(0)
    , discount_factor(0.0)
    , max_nondef_actions(0)  {
  (void)_alloc;
    }



   typedef int32_t _horizon_type;
  _horizon_type horizon;

   typedef float _discount_factor_type;
  _discount_factor_type discount_factor;

   typedef int32_t _max_nondef_actions_type;
  _max_nondef_actions_type max_nondef_actions;





  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRDDLParamsResponse_

typedef ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<std::allocator<void> > GetRDDLParamsResponse;

typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLParamsResponse > GetRDDLParamsResponsePtr;
typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetRDDLParamsResponse const> GetRDDLParamsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.horizon == rhs.horizon &&
    lhs.discount_factor == rhs.discount_factor &&
    lhs.max_nondef_actions == rhs.max_nondef_actions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_knowledge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0cf0ef8b4c4b342e8f951535dfe54dba";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0cf0ef8b4c4b342eULL;
  static const uint64_t static_value2 = 0x8f951535dfe54dbaULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_knowledge_msgs/GetRDDLParamsResponse";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 horizon\n"
"float32 discount_factor\n"
"int32 max_nondef_actions\n"
"\n"
"\n"
;
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.horizon);
      stream.next(m.discount_factor);
      stream.next(m.max_nondef_actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRDDLParamsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_knowledge_msgs::GetRDDLParamsResponse_<ContainerAllocator>& v)
  {
    s << indent << "horizon: ";
    Printer<int32_t>::stream(s, indent + "  ", v.horizon);
    s << indent << "discount_factor: ";
    Printer<float>::stream(s, indent + "  ", v.discount_factor);
    s << indent << "max_nondef_actions: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_nondef_actions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETRDDLPARAMSRESPONSE_H
