// Generated by gencpp from file rosplan_knowledge_msgs/StatusUpdate.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_STATUSUPDATE_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_STATUSUPDATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_knowledge_msgs
{
template <class ContainerAllocator>
struct StatusUpdate_
{
  typedef StatusUpdate_<ContainerAllocator> Type;

  StatusUpdate_()
    : last_update_client()
    , last_update_time()  {
    }
  StatusUpdate_(const ContainerAllocator& _alloc)
    : last_update_client(_alloc)
    , last_update_time()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _last_update_client_type;
  _last_update_client_type last_update_client;

   typedef ros::Time _last_update_time_type;
  _last_update_time_type last_update_time;





  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> const> ConstPtr;

}; // struct StatusUpdate_

typedef ::rosplan_knowledge_msgs::StatusUpdate_<std::allocator<void> > StatusUpdate;

typedef boost::shared_ptr< ::rosplan_knowledge_msgs::StatusUpdate > StatusUpdatePtr;
typedef boost::shared_ptr< ::rosplan_knowledge_msgs::StatusUpdate const> StatusUpdateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator2> & rhs)
{
  return lhs.last_update_client == rhs.last_update_client &&
    lhs.last_update_time == rhs.last_update_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_knowledge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "184cadf1052e240c262af1a764339990";
  }

  static const char* value(const ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x184cadf1052e240cULL;
  static const uint64_t static_value2 = 0x262af1a764339990ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_knowledge_msgs/StatusUpdate";
  }

  static const char* value(const ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A message used to publish a status notification from the Knowledge Base\n"
"# This status notifies that the KB has been updated.\n"
"\n"
"string last_update_client\n"
"time last_update_time\n"
"\n"
;
  }

  static const char* value(const ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.last_update_client);
      stream.next(m.last_update_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StatusUpdate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_knowledge_msgs::StatusUpdate_<ContainerAllocator>& v)
  {
    s << indent << "last_update_client: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.last_update_client);
    s << indent << "last_update_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.last_update_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_STATUSUPDATE_H
